nome = input('Digite algo:')
print('O tipo primitivo deste valor é:', type(nome))
print('Há somente espaços?', nome.isspace())
print('É um número?', nome.isnumeric())
print('É alfabetico?', nome.isalpha())
print('É alfanumérico?', nome.isalnum())
print('Está em maiusculas?', nome.isupper())
print('Está em minusculas?', nome.islower())
print('Está capitalizada?', nome.istitle()) 